---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: deps
          release: patch
        - type: perf
          release: patch
        - type: chore
          release: false
        - type: docs
          release: false
        - type: ci
          release: false
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      writerOpts:
        mainTemplate: |
          {{> header}}

          {{#each commitGroups}}

          {{#if title}}
          ### {{title}}

          {{/if}}
          {{#each commits}}
          {{> commit root=@root}}
          {{/each}}

          {{/each}}
          {{> footer}}
        headerPartial: |
          {{#if isPatch~}}
            ##
          {{~else~}}
            #
          {{~/if}} {{#if @root.linkCompare~}}
            [{{version}}](
            {{~#if @root.repository~}}
              {{~#if @root.host}}
                {{~@root.host}}/
              {{~/if}}
              {{~#if @root.owner}}
                {{~@root.owner}}/
              {{~/if}}
              {{~@root.repository}}
            {{~else}}
              {{~@root.repoUrl}}
            {{~/if~}}
            /compare/{{previousTag}}...{{currentTag}})
          {{~else}}
            {{~version}}
          {{~/if~}}
          {{~#if title}} "{{title}}"
          {{~/if}}
          {{~#if date}} ({{date}})
          {{/if}}
        footerPartial: |
          {{#if noteGroups}}
          {{#each noteGroups}}

          ### {{title}}

          {{#each notes}}
          * {{#if commit.scope}}**{{commit.scope}}:** {{/if}}{{text}}
          {{/each}}
          {{/each}}

          {{/if}}
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: deps
            section: Dependency Updates
          - type: perf
            section: Performance Improvements
          - type: docs
            section: Documentation
          - type: ci
            section: Continuous Integration
          - type: chore
            hidden: true
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
      assets:
        - CHANGELOG.md
  - "@semantic-release/github"
