---
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
name: publish
jobs:
  main:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"

      - name: Update local package version
        run: npm --no-git-tag-version version "${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
